DROP DATABASE IF EXISTS GESTION_HARBEST;
CREATE DATABASE GESTION_HARBEST;
USE GESTION_HARBEST;

SET GLOBAL event_scheduler = ON;
SET SQL_SAFE_UPDATES = 0;

/*TABLA USUARIOS*/
CREATE TABLE USUARIOS
(
IDUsuario INT AUTO_INCREMENT PRIMARY KEY,
Email VARCHAR(50) NOT NULL UNIQUE,
Nombres VARCHAR(20) NOT NULL,
Apellidos VARCHAR(20) NOT NULL,
Clave VARBINARY(100) NOT NULL,
Privilegios JSON NOT NULL,
CClave ENUM('T','F') NOT NULL DEFAULT 'F',
Estatus ENUM('T','F') NOT NULL DEFAULT 'T',
);

