DROP DATABASE IF EXISTS GESTION_HARBEST;
CREATE DATABASE GESTION_HARBEST;
USE GESTION_HARBEST;

SET GLOBAL event_scheduler = ON;
SET SQL_SAFE_UPDATES = 0;

/*TABLA USUARIOS*/
CREATE TABLE USUARIOS
(
IDUsuario INT AUTO_INCREMENT PRIMARY KEY,
Email VARCHAR(50) NOT NULL UNIQUE,
Nombres VARCHAR(20) NOT NULL,
Apellidos VARCHAR(20) NOT NULL,
Clave VARBINARY(100) NOT NULL,
Privilegios JSON NOT NULL,
CClave ENUM('T','F') NOT NULL DEFAULT 'F',
Estatus ENUM('T','F') NOT NULL DEFAULT 'T',
);

DELIMITER $$
CREATE PROCEDURE `SP_VALIDAR_LOGIN` (
    IN in_EMAIL VARCHAR(50),
    IN in_CLAVE VARCHAR(20)
)
BEGIN
    IF NOT EXISTS (
        SELECT * 
        FROM USUARIOS 
        WHERE Email = in_EMAIL 
        AND CAST(AES_DECRYPT(Clave, in_EMAIL) AS CHAR(50)) = in_CLAVE 
        AND Estatus = 'T') THEN SELECT 	 AS MENSAJE;
    
    ELSE 
        SELECT CClave, IDUsuario, Nombres, Apellidos, Privilegios
        FROM USUARIOS 
        WHERE Email = in_EMAIL;
    END IF;
END $$
